
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "cloud.google.com/go"
  version = "0.17.0"

[[constraint]]
  name = "github.com/Jeffail/gabs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/andybons/gogif"

[[constraint]]
  branch = "master"
  name = "github.com/bradfitz/slice"

[[constraint]]
  branch = "develop"
  name = "github.com/bwmarrin/discordgo"

[[constraint]]
  branch = "master"
  name = "github.com/dghubble/go-twitter"
  source = "github.com/Seklfreak/go-twitter"

[[constraint]]
  name = "github.com/dghubble/oauth1"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/go-redis/cache"
  version = "6.3.1"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.5.4"

[[constraint]]
  name = "github.com/huandu/facebook"
  version = "1.8.1"

[[constraint]]
  branch = "master"
  name = "github.com/lucasb-eyer/go-colorful"

[[constraint]]
  branch = "master"
  name = "github.com/miekg/dns"

[[constraint]]
  branch = "master"
  name = "github.com/nfnt/resize"

[[constraint]]
  branch = "master"
  name = "github.com/olebedev/when"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/renstrom/fuzzysearch"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/Seklfreak/lastfm-go"

[[constraint]]
  branch = "master"
  name = "github.com/ungerik/go-cairo"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "3.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "gopkg.in/oleiade/lane.v1"
  version = "1.0.0"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.0.0"

[[constraint]]
  name = "github.com/inconshreveable/go-keen"
  branch = "v0"

[[constraint]]
  name = "github.com/RichardKnop/machinery"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kennygrant/sanitize"
  version = "1.2.0"

[[constraint]]
  name = "github.com/jzelinskie/geddit"
  branch = "master"

[[constraint]]
  name = "github.com/xuri/excelize"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/Krognol/go-wolfram"

[[constraint]]
  branch = "master"
  name = "github.com/bshuster-repo/logruzio"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/domainr/whois"

[[constraint]]
  branch = "master"
  name = "github.com/dyatlov/go-oembed"

[[constraint]]
  name = "github.com/VojtechVitek/go-trello"
  branch = "master"

[[constraint]]
  name = "github.com/ChimeraCoder/anaconda"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  branch = "master"
  name = "github.com/CleverbotIO/go-cleverbot.io"

[[constraint]]
  name = "github.com/shawntoffel/darksky"
  version = "1.2.0"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "4.0.9"

[[constraint]]
  branch = "master"
  name = "github.com/lucazulian/cryptocomparego"

[[constraint]]
  name = "github.com/stackimpact/stackimpact-go"
  version = "2.3.9"
